name: "python-staging-application"

# Deployment
deployment:
  image: "docker.io/eatherv/python-application"
  tag: "0.0.9" # {"$imagepolicy": "flux-system:python"}
  replicas: "3"
  namespace: "staging"

# Service
service:
  type: "ClusterIP"
